image: registry.gitlab.com/yawik/docker/yarn-git-ssh-rsync:main

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - yarn
    - NODE_ENV=production yarn build
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git stash
    - pm2 deploy ecosystem.config.js production
  only:
  - main
