image: registry.gitlab.com/yawik/docker/yarn-git-ssh-rsync:main

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - yarn
    - NODE_ENV=production yarn build -- --clean
    - pm2 deploy ecosystem.config.js production
  only:
  - main
